# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('pup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descrbtion', models.TextField(max_length=1000)),
                ('pupdate', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sorces', models.TextField(max_length=500)),
                ('objectives', models.TextField(max_length=500)),
                ('pupdate', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField()),
                ('Cources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Cource')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=7)),
                ('collage', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='cource',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Subject'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Cource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Cource'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Lecture'),
        ),
    ]
