# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('pup_date', models.DateTimeField(auto_now_add=True)),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Cource')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_l',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('pup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Cource',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Lecture',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='Cources',
            new_name='cource',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='sorces',
            new_name='sources',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='comment_l',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Lecture'),
        ),
    ]
