# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20161112_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='cource',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
