# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_lecture_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='is_favorite',
        ),
    ]
