# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20161112_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(default='null', max_length=7)),
                ('description', models.TextField(max_length=1000)),
                ('pup_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='cource',
            name='subject',
        ),
        migrations.RenameField(
            model_name='comment_c',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment_l',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='pupdate',
            new_name='pup_date',
        ),
        migrations.RemoveField(
            model_name='comment_c',
            name='cource',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='cource',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.DeleteModel(
            name='Cource',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Subject'),
        ),
        migrations.AddField(
            model_name='comment_c',
            name='course',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='project.Course'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='project.Course'),
        ),
    ]
