# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20161116_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=7),
        ),
    ]
