# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20161116_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.AlterField(
            model_name='comment_c',
            name='body',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='comment_l',
            name='body',
            field=models.TextField(max_length=5000),
        ),
    ]
